### ISSUE TITLE
Need Kinship Community/family backgrounds and icons for community subreddit, twitter, GitHub, etc. accounts.

### ISSUE THREAD

**Issue by m4thfr34k** [KinshipFamily/Tasks#22]

**Comment by m4thfr34k** [comment]
Simply using the official Kin branding/icons could create the perception the Kinship community has an "official" relationship with the Kin Foundation, which we do not.

**Comment by ghost-of-kinerra** [comment]
Solved - moved to its own repo - [ref](https://github.com/KinshipFamily/brand-identity). Please close #22.
